import '@/app/globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

export const metadata = {
  title: 'MySQL CRUD with NextJS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className='flex flex-col min-h-screen'>

        <Navbar />

        <main className='grow p-4'>
          {children}
        </main>

        <Footer />

      </body>
    </html>
  )
}
